version: 2.1

jobs:
  build:
    working_directory: ~/unittest
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Clean and Build
          command: mvn -f unittest/pom.xml clean package

      - run:
          name: Unit Test
          command: mvn -f unittest/pom.xml -Dtest=com.mayab.quality.unittest.service.UserServiceTest

workflows:
  build_and_test:
    jobs:
      - build
      
