version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.9

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Clean and Build
          command: mvn -f unittest/pom.xml clean package -DskipTests

  unit_test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: mvn -f unittest/pom.xml test -Dtest=com.mayab.quality.unittest.service.UserServiceTest
      - store_test_results:
          path: unittest/target/surefire-reports
      - store_artifacts:
          path: unittest/target/surefire-reports
          destination: unit-test-results

  integration_test:
    docker:
      - image: cimg/openjdk:17.0
      - image: circleci/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calidad2024
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    steps:
      - checkout
      - run:
          name: Wait for MySQL to Start
          command: |
            for i in $(seq 1 30); do
              nc -z localhost 3306 && echo "MySQL is up!" && break
              echo "Waiting for MySQL..."
              sleep 1
            done
            if ! nc -z localhost 3306; then
              echo "MySQL failed to start." && exit 1
            fi
      - run:
          name: Run Integration Tests
          command: mvn -f unittest/pom.xml failsafe:integration-test -Dtest=com.mayab.quality.integration.UserServiceTest
      - store_test_results:
          path: unittest/target/failsafe-reports
      - store_artifacts:
          path: unittest/target/failsafe-reports
          destination: integration-test-results

  selenium_test:
    docker: 
      - image: cimg/openjdk:17.0-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Run Selenium Functional Tests
          command: mvn -f unittest/pom.xml verify -Dtest=com.mayab.quality.functional.CRUDSeleniumTest
      - run:
          name: Prepare Screenshots for Publishing
          command: |
            mkdir -p screenshots
            if ls unittest/src/screenshots/* 1> /dev/null 2>&1; then
              cp unittest/src/screenshots/* screenshots/
            else
              echo "No screenshots found to copy."
            fi
      - store_artifacts:
          path: screenshots
          destination: functional-test-screenshots
      - store_test_results:
          path: unittest/target/surefire-reports

  deploy:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: echo "Deploying application to production..."
      - run:
          name: Publish Results to GitHub Pages
          command: |
            git config --global user.email "marco.winistorfer@anahuac.mx"
            git config --global user.name "marcowini"
            git checkout -b gh-pages || git checkout gh-pages
            mkdir -p screenshots  # Ensure screenshots directory exists
            if [ -d "screenshots" ] && [ "$(ls -A screenshots)" ]; then
              cp -r screenshots/* .
              echo "<html><body><h1>Test Results</h1><ul>" > index.html
              for file in screenshots/*; do
                echo "<li><a href='$file'>$(basename $file)</a></li>" >> index.html
              done
              echo "</ul></body></html>" >> index.html
              git add .
              git commit -m "Update test results with screenshots"
              git push -f https://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@github.com/marcowini/marcowinistoerferunittest.git gh-pages
            else
              echo "No screenshots to publish. Skipping this step."
            fi

workflows:
  build_and_test_and_deploy:
    jobs:
      - build-and-test
      - unit_test:
          requires:
            - build-and-test
      - integration_test:
          requires:
            - unit_test
      - selenium_test:
          requires:
            - integration_test
      - deploy:
          requires:
            - selenium_test
          filters:
            branches:
              only: main
