version: 2.1

jobs:
  build:
    working_directory: ~/circleci-java
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build Project
          command: mvn install -DskipTests

  unit_test:
    working_directory: ~/circleci-java
    docker:
      - image: "circleci/openjdk:17"
    steps:
      - checkout
      - run:
          name: Run Unit Tests (UserServiceTest)
          command: mvn test -Dtest=UserServiceTest

  integration_test:
    working_directory: ~/circleci-java
    docker:
      - image: "circleci/openjdk:17"
      - image: "circleci/mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calidad2024
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    steps:
      - checkout
      - run:
          name: Wait for MySQL to Start
          command: |
            for i in `seq 1 30`; do
              nc -z localhost 3306 && echo "MySQL is up!" && break
              echo "Waiting for MySQL..."
              sleep 1
            done
      - run:
          name: Run Integration Tests (UserServiceTest)
          command: mvn failsafe:integration-test -Dit.test=UserServiceTest

  selenium_test:
    working_directory: ~/circleci-java
    docker:
      - image: "circleci/openjdk:17"
      - image: selenium/standalone-chrome:latest
    steps:
      - checkout
      - run:
          name: Run Selenium Functional Tests (CRUD)
          command: mvn verify -P selenium -Dtest=CRUDTest

  deployment:
    working_directory: ~/circleci-java
    docker:
      - image: "circleci/openjdk:17"
    steps:
      - run:
          name: Deployment Placeholder
          command: echo "Deployment done!"

workflows:
  build_and_test:
    jobs:
      - build
      - unit_test:
          requires:
            - build
      - integration_test:
          requires:
            - unit_test
      - selenium_test:
          requires:
            - integration_test
      - deployment:
          requires:
            - selenium_test
          filters:
            branches:
              only:
                - master
